name: wallpaper
description: "A new Flutter app for live wallpapers using Pexels API."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  dio:
  cached_network_image: 
  flutter_staggered_grid_view: 
  external_path: 
  media_scanner:
  wallpaper_manager_flutter:   
  path_provider:
  flutter_launcher_icons:
  video_thumbnail:
  video_player:
  permission_handler: 
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/logo.png"  